[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
private_confession_addr ='0x9a2c7b00834e5d597e2545ef1bfbeb8af1e2b84e5025006c8a1cdc479fbb3d30'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]